apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
        - name: quote-app
          image: quote-app:local
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5

        